language: node_js

node_js:
  - lts/carbon

install:
  - npm install

script:
  - npm run start

cache:
  directories:
  - node_modules

deploy:
  provider: npm
  email: marcoboffo.waves@gmail.com
  skip_cleanup: true
  api_key:
    secure: O232hq84yuYDU7vXTXc8Mu9UFdEL7rpA/9b+E8WDd4O7m/BWbeHdG1VTLK4FHq2jP27jekVGB1WpmrM+wiSg5TpYm0l0540iqadv6x1VBGeEkTdY44M3I93UbmDa6rM7w9vxdU3jm2LweS59PnXWeKAMDQ3FKlDKnIL/Rw1eKGlAVdRDFGY2lMpMmQQNvLXXMCchcceLDLAElcIRPi3CGpjYttpTlFbTayaRkObwHuZphCOB/9e3t/0ZtCM5W9iWBe6F+2+WoOLgL+qMVv7b1r458CWR3wS7FyLzT/jg9sl06Uqhcau6W29HfH2RnCYuS4uuNIITtDRKn6xOGLJr3XmJbhsqTDGVk6ybvnI20ltkOXZNDaMFYrWaEN+ibl/2c4itGUTsUg/EAMV7s37+W3rcB0Q3BPFXw3zFDT0AyVEpXpo6hvcti+leodZ2JA6CUco/KHPov31lfr6zh7B+TyFNQrFJeAVKTLng5TLJlkPQOe3fVFrZZmqKaD+s73EI/kGvgwclcoWqu2pVoEE/S7x6lwKFsT4nmw8Q0AGuJ2YTOTNw2Ky0S1siBeEFAlThST9HqaGL9qwDHOiO/4E1croGpuJjT6Xf472H43orCP+s9RFg506I9+Qy0cq2qI+ouBk7EIqpxdTAt/Rm55RnDVMjyj7moIbM2QzEgrWeR+8=
  on:
    tags: true
    repo: scaccogatto/vue-viewports
